#!/usr/bin/env -S deno run -A
import { conditions, step, workflow } from "jsr:@david/gagen@^0.5.0";

const pluginName = "dprint-plugin-roslyn";

interface Profile {
  /** dprint platform identifier */
  platform: string;
  /** dotnet --runtime value */
  dotnetRuntime: string;
  /** rust target triple used in the zip name */
  target: string;
}

const profiles: Profile[] = [
  { platform: "darwin-x86_64", dotnetRuntime: "osx-x64", target: "x86_64-apple-darwin" },
  { platform: "darwin-aarch64", dotnetRuntime: "osx-arm64", target: "aarch64-apple-darwin" },
  { platform: "linux-x86_64", dotnetRuntime: "linux-x64", target: "x86_64-unknown-linux-gnu" },
  { platform: "linux-x86_64-musl", dotnetRuntime: "linux-musl-x64", target: "x86_64-unknown-linux-musl" },
  { platform: "linux-aarch64", dotnetRuntime: "linux-arm64", target: "aarch64-unknown-linux-gnu" },
  { platform: "linux-aarch64-musl", dotnetRuntime: "linux-musl-arm64", target: "aarch64-unknown-linux-musl" },
  { platform: "windows-x86_64", dotnetRuntime: "win-x64", target: "x86_64-pc-windows-msvc" },
];

const isTag = conditions.isTag();

const zipFor = (p: Profile) => `${pluginName}-${p.target}.zip`;

const getTagVersion = step({
  id: "get_tag_version",
  name: "Get tag version",
  if: isTag,
  run: "echo TAG_VERSION=${GITHUB_REF/refs\\/tags\\//} >> $GITHUB_OUTPUT",
  outputs: ["TAG_VERSION"],
});

workflow({
  name: "CI",
  on: {
    pull_request: { branches: ["main"] },
    push: { branches: ["main"], tags: ["*"] },
  },
  jobs: [{
    id: "build",
    name: "test_release",
    runsOn: "macos-14",
    // id-token: write is required for npm --provenance
    permissions: { contents: "write", "id-token": "write" },
    steps: [
      { name: "Checkout", uses: "actions/checkout@v6" },
      { uses: "denoland/setup-deno@v2" },
      {
        uses: "actions/setup-dotnet@v5",
        with: { "dotnet-version": "10.0.x" },
      },
      {
        uses: "actions/setup-node@v4",
        with: { "node-version": "22.x", "registry-url": "https://registry.npmjs.org" },
      },
      {
        name: "Build (Debug)",
        run: "dotnet build DprintPluginRoslyn",
      },
      { name: "Test", run: "dotnet test" },
      { name: "Test Exe", run: "cd test && cargo test" },
      {
        name: "Build (Release)",
        run: profiles.map((p) =>
          `dotnet build DprintPluginRoslyn -c Release --self-contained --runtime ${p.dotnetRuntime}`
        ),
      },
      {
        name: "Package",
        // cd into each output directory so we only include its files
        run: [
          "RELEASE_DIR=$GITHUB_WORKSPACE/DprintPluginRoslyn/bin/Release/net10.0",
          ...profiles.flatMap((p) => [
            `cd $RELEASE_DIR/${p.dotnetRuntime}`,
            `zip -r ../../../../../${zipFor(p)} ./*`,
          ]),
        ],
      },
      {
        name: "Create plugin file",
        run: "deno run --allow-read=. --allow-write=. scripts/create_plugin_file.ts",
      },
      getTagVersion,
      {
        name: "Build npm packages",
        if: isTag,
        run: "deno run -A scripts/create_npm_packages.ts",
      },
      {
        name: "Create release notes",
        if: isTag,
        run:
          `deno run -A ./scripts/generate_release_notes.ts ${getTagVersion.outputs.TAG_VERSION} > \${{ github.workspace }}-CHANGELOG.txt`,
      },
      {
        name: "Release",
        if: isTag,
        uses: "softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844",
        env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
        with: {
          files: [...profiles.map(zipFor), "plugin.json"].join("\n"),
          body_path: "${{ github.workspace }}-CHANGELOG.txt",
          draft: false,
        },
      },
      {
        // npm trusted publishing (OIDC) requires npm >= 11.5.1.
        name: "Upgrade npm",
        if: isTag,
        run: "npm install --global npm@latest",
      },
      {
        name: "Publish npm packages",
        if: isTag,
        run: "deno run -A scripts/publish_npm_packages.ts",
      },
    ],
  }],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header: "# GENERATED BY ./ci.ts -- DO NOT DIRECTLY EDIT",
  pinDeps: true,
});
